Rodrigo menacho/camelcasemethod
AT-08/coding pull request #35
Opened 2018-10-03 18:24 UTC by Warchino

2018-10-04 18:10 UTC, carledriss commented on config/checkstyle/checkstyle.xml
> -</module>
Why did you modify this config file ?

2018-10-04 18:11 UTC, carledriss commented on src/main/java/org/fundacionjala/coding/camelcase/Solution.java
> +                    words[i] = words[i].substring(0, 1).toUpperCase() + words[i].substring(1);
Don't concatenate strings using +

2018-10-04 18:36 UTC, Warchino commented on config/checkstyle/checkstyle.xml
> -</module>
I didn't modify that archive.

2018-10-04 19:25 UTC, carledriss requested changes
Don't forget to increase the code coverage

2018-10-05 12:33 UTC, carledriss requested changes
Please increase the code coverage.
https://codecov.io/gh/AT-08/coding/pull/35/diff?src=pr&el=tree#diff-c3JjL21haW4vamF2YS9vcmcvZnVuZGFjaW9uamFsYS9jb2RpbmcvY2FtZWxjYXNlL1NvbHV0aW9uLmphdmE=

2018-10-08 15:39 UTC, carledriss approved these changes
LGTM! 👍

2018-10-08 15:39 UTC, merged